---
# Set default variables
- import_tasks: set-default-variables.yml

- name: Ensure the APT cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common packages
  apt:
    package: "{{ space_common_packages }}"

- name: Purge unneeded services
  apt:
    package: "{{ space_unneeded_packages }}"
    state: "absent"
    purge: yes
    autoremove: yes

- name: Perform a full system upgrade
  apt:
    upgrade: "safe"

- name: Generate the unattended-upgrades templates to enable automatic security updates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: "20auto-upgrades.j2",       dest: "/etc/apt/apt.conf.d/20auto-upgrades" }
    - { src: "50unattended-upgrades.j2", dest: "/etc/apt/apt.conf.d/50unattended-upgrades" }

- name: Apply the custom sysctl values
  include_role:
    name: sysctl
