#!/bin/bash

# exit on errors
set -e

runpost() {
  popd
  . scripts/post.sh
}

# kill ssh tunnel when exiting
trap "exit" INT TERM ERR
trap "runpost; kill 0" EXIT

. scripts/pre.sh

# get oasis
if [[ ! -d "$HOME/.space-elevator/oasis" ]]; then
  mkdir -p "$HOME/.space-elevator"
  git clone https://github.com/fraction/oasis.git "$HOME/.space-elevator/oasis"
  fresh=1
fi

pushd "$HOME/.space-elevator/oasis"

# a known good state
. "$MAIN_DIR/scripts/settle.sh" "fc33705" "$fresh"

# ssh tunnel ssb stuff AND blobs
ssh -NL 8008:localhost:8008 -L 8989:localhost:8989 "spaceman@$IP" &

# run it
echo "Starting Oasis..."
npm start -- "$@" --host localhost
