#!/bin/bash

# exit on errors
set -e

# kill ssh tunnel when exiting
trap "exit" INT TERM ERR
trap "kill 0" EXIT

. scripts/pre.sh

# get patchbay
if [[ ! -d "$HOME/.space-elevator/patchbay" ]]; then
  mkdir -p "$HOME/.space-elevator"
  git clone https://github.com/ssbc/patchbay "$HOME/.space-elevator/patchbay"
  pushd "$HOME/.space-elevator/patchbay"
  # a known good state
  git checkout 4d1001442a68d2f9cb1521459e02e3587f312ebf
  npm i
else
  pushd "$HOME/.space-elevator/patchbay"
fi

git checkout -- . # return everything to defaults
git pull origin master # update code

# a known good state
git checkout 4d1001442a68d2f9cb1521459e02e3587f312ebf

# ssh tunnel
ssh -NL 8008:localhost:8008 "spaceman@$IP" &

# run it
echo "Starting Patchbay..."
npm run lite > /dev/null 2>&1
popd

. scripts/post.sh
