#!/bin/bash

# exit on errors
set -e

runpost() {
  popd
  . scripts/post.sh
}

# kill ssh tunnel when exiting
trap "exit" INT TERM ERR
trap "runpost; kill 0" EXIT

. scripts/pre.sh

# get patchbay
if [[ ! -d "$HOME/.space-elevator/patchbay" ]]; then
  mkdir -p "$HOME/.space-elevator"
  git clone https://github.com/ssbc/patchbay "$HOME/.space-elevator/patchbay"
  pushd "$HOME/.space-elevator/patchbay"
  # a known good state
  git checkout 4d1001442a68d2f9cb1521459e02e3587f312ebf
  npm i
else
  pushd "$HOME/.space-elevator/patchbay"
fi


# a known good state
git fetch
git checkout 4d1001442a68d2f9cb1521459e02e3587f312ebf
git checkout -- . # return everything to defaults

# ssh tunnel ssb stuff AND blobs
ssh -NL 8008:localhost:8008 -L 8989:localhost:8989 "spaceman@$IP" &

# run it
echo "Starting Patchbay..."
npm run lite > /dev/null 2>&1
