#!/bin/bash

# exit on errors
set -e

runpost() {
  popd
  . scripts/post.sh
}

# kill ssh tunnel when exiting
trap "exit" INT TERM ERR
trap "runpost; kill 0" EXIT

. scripts/pre.sh

if [[ ! -d "$HOME/.space-elevator/scat" ]]; then
  mkdir -p "$HOME/.space-elevator"
  git clone https://github.com/stripedpajamas/scat "$HOME/.space-elevator/scat"
  pushd "$HOME/.space-elevator/scat"
  npm i
else
  pushd "$HOME/.space-elevator/scat"
fi

# a known good state
git fetch
git checkout v1.7.4
git checkout -- . # return everything to defaults

# ssh tunnel
ssh -NL 8008:localhost:8008 "spaceman@$IP" &

# run it
echo "Starting Scat..."
npm start -- "$@" --host localhost
