#!/bin/bash

# exit on errors
set -e

# kill ssh tunnel when exiting
trap "exit" INT TERM ERR
trap "kill 0" EXIT

. scripts/pre.sh


if [[ ! -d "$HOME/.space-elevator/scat" ]]; then
  mkdir -p "$HOME/.space-elevator"
  git clone https://github.com/stripedpajamas/scat "$HOME/.space-elevator/scat"
  pushd "$HOME/.space-elevator/scat"
  npm i
else
  pushd "$HOME/.space-elevator/scat"
fi

git checkout -- . # return everything to defaults
git pull origin master # update code

# a known good state
git checkout 6aa00b830e23da6e572ac1ac350e8c0375d272ec

# ssh tunnel
ssh -NL 8008:localhost:8008 "spaceman@$IP" &

# run it
echo "Starting Scat..."
npm start
popd

. scripts/post.sh
