#!/usr/bin/env node

const os = require('os')
const path = require('path')
const { spawn } = require('child_process')

function help () {
  console.log('Usage: spel <provision|patchbay>')
}

function provision () {
  spawn(path.join(__dirname, 'provision'), { stdio: 'inherit' })
}

function patchbay () {
  spawn(path.join(__dirname, 'patchbay'), { stdio: 'inherit' })
}

function cleanup () {
  spawn(path.join(__dirname, 'cleanup'), { stdio: 'inherit' })
}

async function main () {
  const cmd = process.argv[2]
  switch (cmd) {
    case 'provision':
      provision()
      break
    case 'patchbay':
      patchbay()
      break
    case 'cleanup':
      cleanup()
      break
    default:
      help()
      break
  }
}

main()
