#!/usr/bin/env node

const path = require('path')
const { spawn } = require('child_process')

function help () {
  console.log('Usage: spel <provision|patchbay|scat>')
}

function provision () {
  spawn(path.join(__dirname, 'provision'), { stdio: 'inherit', cwd: __dirname })
}

function patchbay () {
  spawn(path.join(__dirname, 'patchbay'), { stdio: 'inherit', cwd: __dirname })
}

function scat () {
  spawn(path.join(__dirname, 'scat'), { stdio: 'inherit', cwd: __dirname })
}

function cleanup () {
  spawn(path.join(__dirname, 'cleanup'), { stdio: 'inherit', cwd: __dirname })
}

async function main () {
  const cmd = process.argv[2]
  switch (cmd) {
    case 'provision':
      provision()
      break
    case 'patchbay':
      patchbay()
      break
    case 'scat':
      scat()
      break
    case 'cleanup':
      cleanup()
      break
    default:
      help()
      break
  }
}

main()
