---
space_common_packages:
  # Ensure that Apparmor is installed
  - apparmor
  # Enables support for the HTTPS protocol in APT sources
  - apt-transport-https
  # Used to perform a system upgrade
  - aptitude
  - build-essential
  - curl
  - expect
  # Legacy GPG is required by the Ansible apt_repository task
  - gnupg
  # Used to configure firewall rules
  - iptables
  # Used for documentation generation
  - markdown
  # Ensures the server's clock is set properly
  - ntp
  # Required to use the Ansible `expect` module
  - python-pexpect
  # Required for the apt_repository module
  - software-properties-common
  # Used for automatically installing security updates
  - unattended-upgrades
  # Install git for source code retrieval and use with "go get" command
  - git

# Services that are running by default but not needed
space_unneeded_packages:
  - lxd
  - snapd

# By default concurrent executions of `iptables` will fail immediately if unable
# to acquire a lock. We use the `--wait` argument to instead specify a maximum
# number of seconds to wait before failing. This allows multiple services to add
# iptables rules at once. See Issue #950 for longer term ideas on how to make
# this var not required.
space_iptables_wait: 120

# In online documentation, we recommend a URL for people to check
# their effective IP address.

space_my_ip_url: https://duckduckgo.com/?q=ip+address

# Ciphersuites recommended from Mozilla's Modern compatibility profile
# https://wiki.mozilla.org/Security/Server_Side_TLS
space_tls_ciphers: "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256"

apt_repository_retries: 10
apt_repository_delay: 20
