---
- name: Create ssb-service directory
  shell: >
    mkdir -p "{{ ansible_env.HOME }}/ssb-service"
  args:
    executable: "/bin/bash"

- name: Copy server runner for service creation
  copy:
    src: run.sh
    dest: "{{ ansible_env.HOME }}/ssb-service/run.sh"
    owner: spaceman
    group: spaceman
    mode: 0777

- name: Install SSB as a system service
  copy:
    src: ssb.service
    dest: /etc/systemd/system/ssb.service
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Start the SSB service
  shell: >
    systemctl start ssb
  args:
    executable: "/bin/bash"
  become: yes

- name: Wait 5 seconds for the service to come up
  pause:
    seconds: 5

- name: Install SSB plugins
  shell: >
    export NVM_DIR="$HOME/.nvm";
    . $NVM_DIR/nvm.sh;
    for pkg in {ssb-about,ssb-backlinks,ssb-unread,ssb-suggest,ssb-search,ssb-chess-db,ssb-private,ssb-meme,ssb-tags,ssb-identities,ssb-names};
      do ssb-server --host localhost plugins.install $pkg;
    done;
  args:
    executable: "/bin/bash"

- name: Restart SSB service to enable plugins
  shell: >
    systemctl restart ssb
  args:
    executable: "/bin/bash"
  become: yes

