---

- name: Install SSB deps and initialize SSB Server
# ========================================================
  hosts: spacehost
  remote_user: "spaceman"
  become: yes

  roles:
    - nvm
    - ssb
...
